# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SmallScrewdriver/SmallScrewdriverMain.ui'
#
# Created: Thu Aug 06 22:42:22 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_SmallScrewdriverMain(object):
    def setupUi(self, SmallScrewdriverMain):
        SmallScrewdriverMain.setObjectName("SmallScrewdriverMain")
        SmallScrewdriverMain.resize(1443, 1009)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/main/screwdriver.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SmallScrewdriverMain.setWindowIcon(icon)
        self.horizontalLayout_3 = QtGui.QHBoxLayout(SmallScrewdriverMain)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtGui.QGroupBox(SmallScrewdriverMain)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imageList = QtGui.QListView(self.groupBox_2)
        self.imageList.setObjectName("imageList")
        self.verticalLayout.addWidget(self.imageList)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addImages = QtGui.QPushButton(self.groupBox_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/main/list_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addImages.setIcon(icon1)
        self.addImages.setIconSize(QtCore.QSize(24, 24))
        self.addImages.setObjectName("addImages")
        self.horizontalLayout.addWidget(self.addImages)
        self.removeImage = QtGui.QPushButton(self.groupBox_2)
        self.removeImage.setWhatsThis("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/main/trash_green_full.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeImage.setIcon(icon2)
        self.removeImage.setIconSize(QtCore.QSize(24, 24))
        self.removeImage.setShortcut("")
        self.removeImage.setObjectName("removeImage")
        self.horizontalLayout.addWidget(self.removeImage)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(SmallScrewdriverMain)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBoxBinSize = QtGui.QComboBox(self.groupBox)
        self.comboBoxBinSize.setObjectName("comboBoxBinSize")
        self.comboBoxBinSize.addItem("")
        self.comboBoxBinSize.addItem("")
        self.comboBoxBinSize.addItem("")
        self.comboBoxBinSize.addItem("")
        self.comboBoxBinSize.addItem("")
        self.comboBoxBinSize.addItem("")
        self.verticalLayout_2.addWidget(self.comboBoxBinSize)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.tabWidget = QtGui.QTabWidget(SmallScrewdriverMain)
        self.tabWidget.setObjectName("tabWidget")
        self.tabShelfNextFit = QtGui.QWidget()
        self.tabShelfNextFit.setObjectName("tabShelfNextFit")
        self.tabWidget.addTab(self.tabShelfNextFit, "")
        self.tabShelfFirstFit = QtGui.QWidget()
        self.tabShelfFirstFit.setObjectName("tabShelfFirstFit")
        self.tabWidget.addTab(self.tabShelfFirstFit, "")
        self.tabGuillotine = QtGui.QWidget()
        self.tabGuillotine.setObjectName("tabGuillotine")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabGuillotine)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_3 = QtGui.QGroupBox(self.tabGuillotine)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.comboBox = QtGui.QComboBox(self.groupBox_3)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_6.addWidget(self.comboBox)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.tabGuillotine)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.comboBox_2 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout_5.addWidget(self.comboBox_2)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        spacerItem = QtGui.QSpacerItem(20, 197, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.tabWidget.addTab(self.tabGuillotine, "")
        self.tabMaxRects = QtGui.QWidget()
        self.tabMaxRects.setObjectName("tabMaxRects")
        self.tabWidget.addTab(self.tabMaxRects, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.start = QtGui.QPushButton(SmallScrewdriverMain)
        self.start.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/main/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start.setIcon(icon3)
        self.start.setIconSize(QtCore.QSize(128, 128))
        self.start.setObjectName("start")
        self.horizontalLayout_2.addWidget(self.start)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_5 = QtGui.QGroupBox(SmallScrewdriverMain)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scale = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.scale.setMinimum(0.05)
        self.scale.setMaximum(10.0)
        self.scale.setSingleStep(0.05)
        self.scale.setProperty("value", 1.0)
        self.scale.setObjectName("scale")
        self.verticalLayout_8.addWidget(self.scale)
        self.verticalLayout_7.addWidget(self.groupBox_5)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)

        self.retranslateUi(SmallScrewdriverMain)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(SmallScrewdriverMain)

    def retranslateUi(self, SmallScrewdriverMain):
        SmallScrewdriverMain.setWindowTitle(QtGui.QApplication.translate("SmallScrewdriverMain", "Маленькая отвёртка - упаковщик текстур", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("SmallScrewdriverMain", "Изображения", None, QtGui.QApplication.UnicodeUTF8))
        self.addImages.setToolTip(QtGui.QApplication.translate("SmallScrewdriverMain", "Добавить папку с изображениями", None, QtGui.QApplication.UnicodeUTF8))
        self.addImages.setText(QtGui.QApplication.translate("SmallScrewdriverMain", "Добавить", None, QtGui.QApplication.UnicodeUTF8))
        self.removeImage.setToolTip(QtGui.QApplication.translate("SmallScrewdriverMain", "Убрать выделенное изображение", None, QtGui.QApplication.UnicodeUTF8))
        self.removeImage.setText(QtGui.QApplication.translate("SmallScrewdriverMain", "Убрать", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("SmallScrewdriverMain", "Максимальный размер атласов", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxBinSize.setItemText(0, QtGui.QApplication.translate("SmallScrewdriverMain", "256 x 256", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxBinSize.setItemText(1, QtGui.QApplication.translate("SmallScrewdriverMain", "512 x 512", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxBinSize.setItemText(2, QtGui.QApplication.translate("SmallScrewdriverMain", "1024 x 1024", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxBinSize.setItemText(3, QtGui.QApplication.translate("SmallScrewdriverMain", "2048 x 2048", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxBinSize.setItemText(4, QtGui.QApplication.translate("SmallScrewdriverMain", "4096 x 4096", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxBinSize.setItemText(5, QtGui.QApplication.translate("SmallScrewdriverMain", "8192 x 8192", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabShelfNextFit), QtGui.QApplication.translate("SmallScrewdriverMain", "Shelf Next Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabShelfFirstFit), QtGui.QApplication.translate("SmallScrewdriverMain", "Shelf First Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("SmallScrewdriverMain", "Эвристика выбора", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("SmallScrewdriverMain", "Best Area Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("SmallScrewdriverMain", "Best Short Side Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("SmallScrewdriverMain", "Best Long Side Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("SmallScrewdriverMain", "Worst Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("SmallScrewdriverMain", "Правило разделения", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(0, QtGui.QApplication.translate("SmallScrewdriverMain", "Shorter Axis Split", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(1, QtGui.QApplication.translate("SmallScrewdriverMain", "Longer Axis Split", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(2, QtGui.QApplication.translate("SmallScrewdriverMain", "Shorter Leftover Axis Split", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(3, QtGui.QApplication.translate("SmallScrewdriverMain", "Longer Leftover Axis Split", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(4, QtGui.QApplication.translate("SmallScrewdriverMain", "Max Area Split", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(5, QtGui.QApplication.translate("SmallScrewdriverMain", "Min Area Split", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGuillotine), QtGui.QApplication.translate("SmallScrewdriverMain", "Guillotine", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMaxRects), QtGui.QApplication.translate("SmallScrewdriverMain", "Max Rects", None, QtGui.QApplication.UnicodeUTF8))
        self.start.setToolTip(QtGui.QApplication.translate("SmallScrewdriverMain", "Поехали!", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("SmallScrewdriverMain", "Масштаб", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
